spring:
  application:
    name: notification-service
  config:
    import: "configserver:${CONFIG_SERVER_URL:http://localhost:8888}"
  mail:
    host: fake-smtp
    port: 25
    username: ${MAIL_USERNAME:dummy}
    password: ${MAIL_PASSWORD:dummy}

eureka:
  client:
    service-url:
      defaultZone: http://discovery-service:8761/eureka/
  instance:
    prefer-ip-address: true
